"""Initial migration with SQLite

Revision ID: 6f3fe0d49cf8
Revises: 
Create Date: 2025-12-03 09:46:06.941893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3fe0d49cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('project_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IMPLEMENTED', name='projectstatus'), nullable=False),
    sa.Column('workflow_status', sa.Enum('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='workflowstatus'), nullable=False),
    sa.Column('funding_needed', sa.Float(), nullable=True),
    sa.Column('funding_spent', sa.Float(), nullable=True),
    sa.Column('uia_region', sa.Enum('SECTION_I', 'SECTION_II', 'SECTION_III', 'SECTION_IV', 'SECTION_V', name='uiaregion'), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('success_factors', sa.Text(), nullable=False),
    sa.Column('other_requirement_text', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_city'), 'projects', ['city'], unique=False)
    op.create_index(op.f('ix_projects_contact_email'), 'projects', ['contact_email'], unique=False)
    op.create_index(op.f('ix_projects_country'), 'projects', ['country'], unique=False)
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=False)
    op.create_index(op.f('ix_projects_uia_region'), 'projects', ['uia_region'], unique=False)
    op.create_index(op.f('ix_projects_workflow_status'), 'projects', ['workflow_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('project_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_sdgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sdg_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_typologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('typology', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_typologies')
    op.drop_table('project_sdgs')
    op.drop_table('project_requirements')
    op.drop_table('project_images')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_workflow_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_uia_region'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_country'), table_name='projects')
    op.drop_index(op.f('ix_projects_contact_email'), table_name='projects')
    op.drop_index(op.f('ix_projects_city'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
